import { EVENT_TYPES } from './config.js';

/**
 * Lista de eventos disputados.
 * type:   EVENT_TYPES value
 * result: top-5 pilotos reales en orden de llegada
 * picks:  pronóstico de cada jugador para las posiciones 1º–5º
 */

export const upcomingEvents = [
  {
    type: EVENT_TYPES.F1,
    round: 13,
    name: 'GP de Miami',
    location: 'Miami International Autodrome',
    date: '3 may 2026',
    deadline: 'dom 3 may, 18:00',
  },
];

export const events = [
  {
    type: EVENT_TYPES.RALLY,
    round: 12,
    name: 'Rally España',
    location: 'Canarias',
    date: '23–26 abr 2026',
    result: ['Ogier', 'Evans', 'Pajari', 'Katsuta', 'Fourmaux'],
    picks: [
      { player: 'Choro',    guesses: ['Ogier',  'Solberg',  'Sordo',   'Evans',       'Katsuta'   ] },
      { player: 'Dani',     guesses: ['Evans',  'Ogier',  'Katsuta',   'Fourmaux', 'Solberg'    ] },
      { player: 'Juanra',   guesses: ['Solberg',  'Ogier',   'Evans',  'Katsuta',       'Neuville'   ] },
      { player: 'Juano',    guesses: ['Ogier',   'Solberg',  'Evans',  'Katsuta',    'Neuville'    ] },
      { player: 'Sarri',    guesses: ['Ogier',  'Evans',  'Solberg',     'Neuville',     'Sordo'   ] },
      { player: 'Lechero',  guesses: ['Ogier',  'Solberg',  'Sordo',   'Katsuta',    'Pajari'    ] },
      { player: 'Cebolla',  guesses: ['Ogier',  'Solberg',   'Evans',  'Katsuta',    'Sordo'    ] },
      { player: 'Amador',   guesses: ['Ogier',  'Solberg',  'Evans',   'Katsuta',       'Neuville'   ] },
      { player: 'Pilili',   guesses: ['Ogier',   'Neuville',  'Sordo',  'Evans',     'Katsuta'   ] },
      { player: 'Calcetin', guesses: ['Ogier',  'Solberg',   'Evans',  'Katsuta',    'Sordo'      ] },
      { player: 'Angel',    guesses: ['Solberg',  'Evans',  'Ogier',  'Katsuta',     'Sordo'      ] },
      { player: 'David',    guesses: ['Evans',  'Ogier',  'Katsuta',     'Pajari',     'Solberg'   ] },
    ],
  },
  {
    type: EVENT_TYPES.MOTO,
    round: 11,
    name: 'MotoGP España',
    location: 'Circuito de Jerez',
    date: '26 abr 2026',
    result: ['A Marquez', 'Bezzecchi', 'Giannantonio', 'Martin', 'Ogura'],
    picks: [
      { player: 'Choro',    guesses: ['M Marquez',  'A Marquez',  'Bezzecchi',   'Giannantonio',       'Martin'   ] },
      { player: 'Dani',     guesses: ['Giannantonio',  'M Marquez',  'A Marquez',   'Bagnaia', 'Fernandez'    ] },
      { player: 'Juanra',   guesses: ['M Marquez',  'A Marquez',   'Giannantonio',  'Bezzecchi',       'Acosta'   ] },
      { player: 'Juano',    guesses: ['A Marquez',   'M Marquez',  'Bezzecchi',  'Giannantonio',    'Acosta'    ] },
      { player: 'Sarri',    guesses: ['A Marquez',  'M Marquez',  'Giannantonio',   'Bezzecchi',    'Martin'    ] },
      { player: 'Lechero',  guesses: ['A Marquez',  'M Marquez',  'Giannantonio',   'Bezzecchi',    'Martin'    ] },
      { player: 'Cebolla',  guesses: ['Bezzecchi',  'M Marquez',   'Martin',  'A Marquez',    'Acosta'    ] },
      { player: 'Amador',   guesses: ['A Marquez',  'M Marquez',  'Giannantonio',   'Bezzecchi',       'Martin'   ] },
      { player: 'Pilili',   guesses: ['-', '-', '-', '-', '-'] },
      { player: 'Calcetin', guesses: ['A Marquez',  'M Marquez',   'Giannantonio',  'Acosta',    'Bezzecchi'      ] },
      { player: 'Angel',    guesses: ['A Marquez',  'M Marquez',  'Bezzecchi',  'Giannantonio',     'Fernandez'      ] },
      { player: 'David',    guesses: ['M Marquez',  'A Marquez',  'Acosta',     'M Marquez',     'Bezzecchi'   ] },
    ],
  },
  {
    type: EVENT_TYPES.RALLY,
    round: 10,
    name: 'Rally Croacia',
    location: 'Croacia',
    date: '10–12 abr 2026',
    result: ['Katsuta', 'Pajari', 'Paddon', 'YRossel', 'LRossel'],
    picks: [
      { player: 'Choro',    guesses: ['Solberg',  'Evans',  'Katsuta',   'Neuville',       'Fourmaux'   ] },
      { player: 'Dani',     guesses: ['Evans',  'Katsuta',  'Neuville',   'Solberg', 'Fourmaux'    ] },
      { player: 'Juanra',   guesses: ['Solberg',  'Evans',   'Katsuta',  'Neuville',       'Pajari'   ] },
      { player: 'Juano',    guesses: ['Solberg',   'Evans',  'Katsuta',  'Fourmaux',    'Pajari'    ] },
      { player: 'Sarri',    guesses: ['Evans',  'Solberg',  'Neuville',     'Katsuta',     'Fourmaux'   ] },
      { player: 'Lechero',  guesses: ['Solberg',  'Evans',  'Katsuta',   'Paddon',    'Fourmaux'    ] },
      { player: 'Cebolla',  guesses: ['Solberg',  'Evans',   'Katsuta',  'Neuville',    'Fourmaux'    ] },
      { player: 'Amador',   guesses: ['Evans',  'Ogier',  'Solberg',   'Katsuta',       'Neuville'   ] },
      { player: 'Pilili',   guesses: ['Evans',   'Katsuta',  'Fourmaux',  'Neuville',     'McErlean'   ] },
      { player: 'Calcetin', guesses: ['Solberg',  'Neuville',   'Evans',  'Katsuta',    'Fourmaux'      ] },
      { player: 'Angel',    guesses: ['Solberg',  'Evans',  'Katsuta',  'Fourmaux',     'Neuville'      ] },
      { player: 'David',    guesses: ['Solberg',  'Evans',  'Neuville',     'Katsuta',     'Pajari'   ] },
    ],
  },
  {
    type: EVENT_TYPES.F1,
    round: 9,
    name: 'GP de Japón',
    location: 'Circuito de Suzuka',
    date: '29 mar 2026',
    result: ['Antonelli', 'Piastri', 'Leclerc', 'Russell', 'Norris'],
    picks: [
      { player: 'Choro',    guesses: ['Antonelli',  'Russell',  'Leclerc',   'Hamilton',       'Norris'   ] },
      { player: 'Dani',     guesses: ['Antonelli',  'Russell',  'Norris',   'Leclerc', 'Piastri'    ] },
      { player: 'Juanra',   guesses: ['Antonelli',  'Russell',   'Leclerc',  'Piastri',       'Hamilton'   ] },
      { player: 'Juano',    guesses: ['Antonelli',   'Russell',  'Leclerc',  'Hamilton',    'Piastri'    ] },
      { player: 'Sarri',    guesses: ['Antonelli',  'Russell',  'Leclerc',  'Piastri',    'Hamilton'   ] },
      { player: 'Lechero',  guesses: ['Russell',  'Antonelli',  'Piastri',   'Leclerc',    'Norris'    ] },
      { player: 'Cebolla',  guesses: ['Antonelli',  'Russell',   'Piastri',  'Norris',    'Leclerc'    ] },
      { player: 'Amador',   guesses: ['Antonelli',  'Russell',  'Leclerc',   'Hamilton',       'Norris'   ] },
      { player: 'Pilili',   guesses: ['-',   '-',  '-',  '-',     '-'   ] },
      { player: 'Calcetin', guesses: ['Antonelli',  'Russell',   'Piastri',  'Norris',    'Leclerc'      ] },
      { player: 'Angel',    guesses: ['Antonelli',  'Leclerc',  'Piastri',  'Norris',     'Leclerc'      ] },
      { player: 'David',    guesses: ['Russell',  'Antonelli',  'Leclerc',     'Piastri',     'Norris'   ] },
    ],
  },
  {
    type: EVENT_TYPES.MOTO,
    round: 8,
    name: 'MotoGP Austin',
    location: 'Circuito de las Américas',
    date: '29 mar 2026',
    result: ['Bezzecchi', 'Martin', 'Acosta', 'Giannantonio', 'M Marquez'],
    picks: [
      { player: 'Choro',    guesses: ['Bezzecchi',  'Martin',  'Bagnaia',   'Giannantonio',       'Acosta'   ] },
      { player: 'Dani',     guesses: ['Bezzecchi',  'Martin',  'Bagnaia',   'Giannantonio', 'Acosta'    ] },
      { player: 'Juanra',   guesses: ['M Marquez',  'Bagnaia',   'Bezzecchi',  'Martin',       'Giannantonio'   ] },
      { player: 'Juano',    guesses: ['Bezzecchi',   'M Marquez',  'Giannantonio',  'Martin',    'Bagnaia'    ] },
      { player: 'Sarri',    guesses: ['M Marquez',  'Bezzecchi',  'Giannantonio',     'Martin',     'Bagnaia'   ] },
      { player: 'Lechero',  guesses: ['Martin',  'Bezzecchi',  'Bagnaia',   'Giannantonio',    'Acosta'    ] },
      { player: 'Cebolla',  guesses: ['-',  '-',   '-',  '-',    '-'    ] },
      { player: 'Amador',   guesses: ['-',  '-',  '-',   '-',       '-'   ] },
      { player: 'Pilili',   guesses: ['Bezzecchi', 'Martin', 'Acosta', 'Giannantonio', 'M Marquez'] },
      { player: 'Calcetin', guesses: ['M Marquez',  'Giannantonio',   'Bezzecchi',  'Martin',    'Bagnaia'      ] },
      { player: 'Angel',    guesses: ['Giannantonio',  'Bagnaia',  'Bezzecchi',  'Acosta',     'Martin'      ] },
      { player: 'David',    guesses: ['Giannantonio',  'Acosta',  'Bagnaia',     'M Marquez',     'Bezzecchi'   ] },
    ],
  },
  {
    type: EVENT_TYPES.MOTO,
    round: 7,
    name: 'MotoGP Brasil',
    location: 'Autódromo Internacional Ayrton Senna',
    date: '22 mar 2026',
    result: ['Bezzecchi', 'Martin', 'Giannantonio', 'M Marquez', 'Ogura'],
    picks: [
      { player: 'Choro',    guesses: ['M Marquez',  'Martin',  'Bezzecchi',   'Giannantonio',       'Bagnaia'   ] },
      { player: 'Dani',     guesses: ['Bezzecchi',  'Martin',  'M Marquez',   'Giannantonio', 'Acosta'    ] },
      { player: 'Juanra',   guesses: ['M Marquez',  'Martin',   'Bezzecchi',  'Giannantonio',       'Acosta'   ] },
      { player: 'Juano',    guesses: ['M Marquez',   'Bezzecchi',  'Giannantonio',  'Martin',    'A Marquez'    ] },
      { player: 'Sarri',    guesses: ['M Marquez',  'Bezzecchi',  'Giannantonio',     'Acosta',     'Martin'   ] },
      { player: 'Lechero',  guesses: ['M Marquez',  'Bezzecchi',  'Martin',   'Giannantonio',    'Ogura'    ] },
      { player: 'Cebolla',  guesses: ['M Marquez',  'Bezzecchi',   'Martin',  'Giannantonio',    'Ogura'    ] },
      { player: 'Amador',   guesses: ['-',  '-',  '-',   '-',       '-'   ] },
      { player: 'Pilili',   guesses: ['-', '-', '-', '-', '-'] },
      { player: 'Calcetin', guesses: ['-',  '-',   '-',  '-',    '-'      ] },
      { player: 'Angel',    guesses: ['M Marquez',  'Giannantonio',  'Martin',  'Bezzecchi',     'A Marquez'      ] },
      { player: 'David',    guesses: ['Bezzecchi',  'Acosta',  'M Marquez',     'Martin',     'Fernandez'   ] },
    ],
  },
  {
    type: EVENT_TYPES.RALLY,
    round: 6,
    name: 'Rally Kenya',
    location: 'kenya',
    date: '12–15 mar 2026',
    result: ['Katsuta', 'Fourmaux', 'Pajari', 'Lappi', 'Virves'],
    picks: [
      { player: 'Choro',    guesses: ['Ogier',  'Evans',  'Solberg',   'Katsuta',       'Neuville'   ] },
      { player: 'Dani',     guesses: ['Evans',  'Neuville',  'Ogier',   'Katsuta', 'Fourmaux'    ] },
      { player: 'Juanra',   guesses: ['Solberg',  'Evans',   'Ogier',  'Neuville',       'Katsuta'   ] },
      { player: 'Juano',    guesses: ['Evans',   'Ogier',  'Solberg',  'Katsuta',    'Neuville'    ] },
      { player: 'Sarri',    guesses: ['Evans',  'Ogier',  'Solberg',     'Katsuta',     'Neuville'   ] },
      { player: 'Lechero',  guesses: ['Ogier',  'Solberg',  'Evans',   'Katsuta',    'Pajari'    ] },
      { player: 'Cebolla',  guesses: ['-',  '-',   '-',  '-',    '-'    ] },
      { player: 'Amador',   guesses: ['Evans',  'Ogier',  'Solberg',   'Katsuta',       'Neuville'   ] },
      { player: 'Pilili',   guesses: ['Evans',   'Ogier',  'Fourmaux',  'Neuville',     'Katsuta'   ] },
      { player: 'Calcetin', guesses: ['Solberg',  'Ogier',   'Katsuta',  'Evans',    'Neuville'      ] },
      { player: 'Angel',    guesses: ['Evans',  'Solberg',  'Ogier',  'Neuville',     'Pajari'      ] },
      { player: 'David',    guesses: ['Evans',  'Solberg',  'Neuville',     'Katsuta',     'Ogier'   ] },
    ],
  },
  {
    type: EVENT_TYPES.F1,
    round: 5,
    name: 'GP de China',
    location: 'Circuito Internacional de Shanghái',
    date: '15 mar 2026',
    result: ['Antonelli', 'Russell', 'Hamilton', 'Leclerc', 'Bearman'],
    picks: [
      { player: 'Choro',    guesses: ['Antonelli',  'Russell',  'Leclerc',   'Hamilton',       'Verstappen'   ] },
      { player: 'Dani',     guesses: ['Russell',  'Antonelli',  'Norris',   'Piastri', 'Leclerc'    ] },
      { player: 'Juanra',   guesses: ['Russell',  'Antonelli',   'Leclerc',  'Hamilton',       'Norris'   ] },
      { player: 'Juano',    guesses: ['Russell',   'Antonelli',  'Hamilton',  'Leclerc',    'Norris'    ] },
      { player: 'Sarri',    guesses: ['Russell',  'Antonelli',  'Hamilton',  'Leclerc',    'Norris'   ] },
      { player: 'Lechero',  guesses: ['Russell',  'Antonelli',  'Leclerc',   'Hamilton',    'Norris'    ] },
      { player: 'Cebolla',  guesses: ['Russell',  'Antonelli',   'Leclerc',  'Hamilton',    'Norris'    ] },
      { player: 'Amador',   guesses: ['Russell',  'Antonelli',  'Hamilton',   'Leclerc',       'Norris'   ] },
      { player: 'Pilili',   guesses: ['-',   '-',  '-',  '-',     '-'   ] },
      { player: 'Calcetin', guesses: ['Russell',  'Antonelli',   'Leclerc',  'Hamilton',    'Piastri'      ] },
      { player: 'Angel',    guesses: ['Russell',  'Leclerc',  'Antonelli',  'Hamilton',     'Piastri'      ] },
      { player: 'David',    guesses: ['Russell',  'Hamilton',  'Leclerc',     'Piastri',     'Norris'   ] },
    ],
  },
  {
    type: EVENT_TYPES.F1,
    round: 4,
    name: 'GP de Australia',
    location: 'Circuito de Albert Park',
    date: '8 mar 2026',
    result: ['Russell', 'Antonelli', 'Leclerc', 'Hamilton', 'Norris'],
    picks: [
      { player: 'Choro',    guesses: ['Russell',  'Antonelli',  'Leclerc',   'Hadjar',       'Piastri'   ] },
      { player: 'Dani',     guesses: ['Russell',  'Antonelli',  'Norris',   'Leclerc', 'Piastri'    ] },
      { player: 'Juanra',   guesses: ['Russell',  'Antonelli',   'Leclerc',  'Hadjar',       'Piastri'   ] },
      { player: 'Juano',    guesses: ['Russell',   'Antonelli',  'Leclerc',  'Hadjar',    'Piastri'    ] },
      { player: 'Sarri',    guesses: ['Russell',  'Antonelli',  'Leclerc',     'Piastri',     'Norris'   ] },
      { player: 'Lechero',  guesses: ['Russell',  'Antonelli',  'Leclerc',   'Piastri',    'Norris'    ] },
      { player: 'Cebolla',  guesses: ['Russell',  'Antonelli',   'Leclerc',  'Piastri',    'Norris'    ] },
      { player: 'Amador',   guesses: ['Russell',  'Leclerc',  'Antonelli',   'Piastri',       'Norris'   ] },
      { player: 'Pilili',   guesses: ['-',   '-',  '-',  '-',     '-'   ] },
      { player: 'Calcetin', guesses: ['Russell',  'Antonelli',   'Leclerc',  'Piastri',    'Norris'      ] },
      { player: 'Angel',    guesses: ['Russell',  'Antonelli',  'Leclerc',  'Piastri',     'Norris'      ] },
      { player: 'David',    guesses: ['Russell',  'Leclerc',  'Antonelli',     'Piastri',     'Norris'   ] },
    ],
  },
  {
    type: EVENT_TYPES.MOTO,
    round: 3,
    name: 'MotoGP Tailandia',
    location: 'Circuito Internacional de Chang',
    date: '1 mar 2026',
    result: ['Bezzecchi', 'Acosta', 'Fernandez', 'Martin', 'Ogura'],
    picks: [
      { player: 'Choro',    guesses: ['Bezzecchi',  'M Marquez',  'Giannantonio',   'Acosta',       'Martin'   ] },
      { player: 'Dani',     guesses: ['M Marquez',  'Acosta',  'Bagnaia',   'A Marquez', 'Ogura'    ] },
      { player: 'Juanra',   guesses: ['M Marquez',  'Acosta',   'Bezzecchi',  'Martin',       'Fernandez'   ] },
      { player: 'Juano',    guesses: ['-',   '-',  '-',  '-',    '-'    ] },
      { player: 'Sarri',    guesses: ['Bezzecchi',  'M Marquez',  'Acosta',     'Giannantonio',     'Fernandez'   ] },
      { player: 'Lechero',  guesses: ['Bezzecchi',  'M Marquez',  'Acosta',   'A Marquez',    'Martin'    ] },
      { player: 'Cebolla',  guesses: ['Bezzecchi',  'M Marquez',   'Acosta',  'A Marquez',    'Fernandez'    ] },
      { player: 'Amador',   guesses: ['M Marquez',  'Bezzecchi',  'Acosta',   'Fernandez',       'A Marquez'   ] },
      { player: 'Pilili',   guesses: ['M Marquez',   'Bezzecchi',  'Acosta',  'Martin',     'A Marquez'   ] },
      { player: 'Calcetin', guesses: ['M Marquez',  'Bezzecchi',   'Acosta',  'Fernandez',    'Martin'      ] },
      { player: 'Angel',    guesses: ['A Marquez',  'Bezzecchi',  'Acosta',  'Fernandez',     'Martin'      ] },
      { player: 'David',    guesses: ['Acosta',  'M Marquez',  'Martin',     'Fernandez',     'Ogura'   ] },
    ],
  },
  {
    type: EVENT_TYPES.RALLY,
    round: 2,
    name: 'Rally Suecia',
    location: 'Suecia',
    date: '12–15 feb 2026',
    result: ['Evans', 'Katsuta', 'Pajari', 'Solberg', 'Fourmaux'],
    picks: [
      { player: 'Choro',    guesses: ['Solberg',  'Evans',  'Neuville',   'Katsuta',       'Fourmaux'   ] },
      { player: 'Dani',     guesses: ['Evans',  'Neuville',  'Lappi',   'Katsuta', 'Pajari'    ] },
      { player: 'Juanra',   guesses: ['Evans',  'Solberg',   'Katsuta',  'Fourmaux',       'Neuville'   ] },
      { player: 'Juano',    guesses: ['Solberg',   'Evans',  'Katsuta',  'Fourmaux',    'Neuville'    ] },
      { player: 'Sarri',    guesses: ['Solberg',  'Evans',  'Katsuta',     'Lappi',     'Neuville'   ] },
      { player: 'Lechero',  guesses: ['Evans',  'Solberg',  'Sesks',   'Katsuta',    'Pajari'    ] },
      { player: 'Cebolla',  guesses: ['Solberg',  'Evans',   'Katsuta',  'Neuville',    'Fourmaux'    ] },
      { player: 'Amador',   guesses: ['Solberg',  'Evans',  'Neuville',   'Katsuta',       'Lappi'   ] },
      { player: 'Pilili',   guesses: ['Evans',   'Solberg',  'McErlean',  'Fourmaux',     'Neuville'   ] },
      { player: 'Calcetin', guesses: ['Solberg',  'Evans',   'Katsuta',  'Lappi',    'Neuville'      ] },
      { player: 'Angel',    guesses: ['Solberg',  'Evans',  'Fourmaux',  'Katsuta',     'Neuville'      ] },
      { player: 'David',    guesses: ['Solberg',  'Evans',  'Neuville',     'Lappi',     'Katsuta'   ] },
    ],
  },
  {
    type: EVENT_TYPES.RALLY,
    round: 1,
    name: 'Rally Monte‑Carlo',
    location: 'Mónaco‑Francia (Alpes)',
    date: '22–25 ene 2026',
    result: ['Solberg', 'Evans', 'Ogier', 'Fourmaux', 'Neuville'],
    picks: [
      { player: 'Choro',    guesses: ['Ogier',  'Evans',  'Neuville',   'Fourmaux',       'Katsuta'   ] },
      { player: 'Dani',     guesses: ['Ogier',  'Evans',  'Neuville',   'Fourmaux', 'Katsuta'    ] },
      { player: 'Juanra',   guesses: ['Ogier',  'Evans',   'Fourmaux',  'Neuville',       'Katsuta'   ] },
      { player: 'Juano',    guesses: ['Ogier',   'Evans',  'Neuville',  'Fourmaux',    'Solberg'    ] },
      { player: 'Sarri',    guesses: ['Ogier',  'Evans',  'Neuville',     'Paddon',     'Solberg'   ] },
      { player: 'Lechero',  guesses: ['Ogier',  'Evans',  'Solberg',   'Katsuta',    'Pajari'    ] },
      { player: 'Cebolla',  guesses: ['Ogier',  'Solberg',   'Evans',  'Neuville',    'Katsuta'    ] },
      { player: 'Amador',   guesses: ['Ogier',  'Evans',  'Neuville',   'Solberg',       'Fourmaux'   ] },
      { player: 'Pilili',   guesses: ['Ogier',   'Neuville',  'Evans',  'Fourmaux',     'McErlean'   ] },
      { player: 'Calcetin', guesses: ['Ogier',  'Neuville',   'Evans',  'Katsuta',    'Fourmaux'      ] },
      { player: 'Angel',    guesses: ['Ogier',  'Solberg',  'Neuville',  'Evans',     'Katsuta'      ] },
      { player: 'David',    guesses: ['Evans',  'Ogier',  'Katsuta',     'Neuville',     'Fourmaux'   ] },
    ],
  },
];
